l_english:
 anb_settings.1.t:0 "Welcome to:\n£settings_main_bg£"
 anb_settings.1.d:0 "§L                                        Sarhal Update  -   EU4 version 1.34.5"
 anb_settings.1.a:0 "£settings_button_regions_menu£"
 anb_settings.1.b:0 "£settings_button_conquerors_menu£"
 anb_settings.1.bx:0 "£settings_button_conquerors_menu_g£"
 anb_settings.1.c:0 "£settings_button_start_game£"
 anb_settings.1.empty:0 "£event_button_settings_empty£"

 anb_settings.2.t:0 "Great Conquerors\n£settings_conqueror_bg£"
 anb_settings.2.d:0 ""
 anb_settings.2.a:0 "£settings_button_no_conqueror_g£"
 anb_settings.2.ax:0 "£settings_button_no_conqueror£"
 anb_settings.2.b:0 "£settings_button_conqueror_g£"
 anb_settings.2.bx:0 "£settings_button_conqueror£"
 anb_settings.2.c:0 "£settings_button_mythical_g£"
 anb_settings.2.cx:0 "£settings_button_mythical£"
 anb_settings.2.dd:0 "£settings_button_conqueror_variance_on£"
 anb_settings.2.ddx:0 "£settings_button_conqueror_variance_off£"
 anb_settings.2.x:0 "£settings_button_back_to_menu_2£"
 
 anb_settings.3.t:0 "£settings_regions_bg£\n    [Root.GetSettingsNorthAelantir]\n    [Root.GetSettingsCannor]\n    [Root.GetSettingsForbiddenPlains]\n    [Root.GetSettingsWestSerpentspine]\n    [Root.GetSettingsHaless]\n    [Root.GetSettingsDeepwoods]\n    [Root.GetSettingsBulwar]\n    [Root.GetSettingsEastSerpentspine]\n    [Root.GetSettingsRahen]\n    [Root.GetSettingsNorthSarhal]\n    [Root.GetSettingsInsyaa]\n    [Root.GetSettingsSouthAelantir]\n    [Root.GetSettingsSouthSarhal]"
 anb_settings.3.d:0 "\n\n\n\n[Root.GetSettingsAlertRed][Root.GetSettingsAlertOrange]"
 anb_settings.3.a:0 "£settings_button_north_aelantir££settings_alert_none£"
 anb_settings.3.ax:0 "£settings_button_north_aelantir_x£[Root.GetSettingsAlertNorthAelantir]"
 anb_settings.3.b:0 "£settings_button_south_aelantir££settings_alert_none£"
 anb_settings.3.bx:0 "£settings_button_south_aelantir_x£[Root.GetSettingsAlertSouthAelantir]"
 anb_settings.3.c:0 "£settings_button_cannor££settings_alert_none£"
 anb_settings.3.cx:0 "£settings_button_cannor_x£[Root.GetSettingsAlertCannor]"
 anb_settings.3.dd:0 "£settings_button_deepwoods££settings_alert_none£"
 anb_settings.3.ddx:0 "£settings_button_deepwoods_x£[Root.GetSettingsAlertDeepwoods]"
 anb_settings.3.e:0 "£settings_button_bulwar££settings_alert_none£"
 anb_settings.3.ex:0 "£settings_button_bulwar_x£[Root.GetSettingsAlertBulwar]"
 anb_settings.3.f:0 "£settings_button_north_sarhal££settings_alert_none£"
 anb_settings.3.fx:0 "£settings_button_north_sarhal_x£[Root.GetSettingsAlertNorthSarhal]"
 anb_settings.3.g:0 "£settings_button_south_sarhal££settings_alert_none£"
 anb_settings.3.gx:0 "£settings_button_south_sarhal_x£[Root.GetSettingsAlertSouthSarhal]"
 anb_settings.3.h:0 "£settings_button_west_serpentspine££settings_alert_none£"
 anb_settings.3.hx:0 "£settings_button_west_serpentspine_x£[Root.GetSettingsAlertWestSerpentspine]"
 anb_settings.3.i:0 "£settings_button_east_serpentspine££settings_alert_none£"
 anb_settings.3.ix:0 "£settings_button_east_serpentspine_x£[Root.GetSettingsAlertEastSerpentspine]"
 anb_settings.3.j:0 "£settings_button_forbidden_plains££settings_alert_none£"
 anb_settings.3.jx:0 "£settings_button_forbidden_plains_x£[Root.GetSettingsAlertForbiddenPlains]"
 anb_settings.3.k:0 "£settings_button_rahen££settings_alert_none£"
 anb_settings.3.kx:0 "£settings_button_rahen_x£[Root.GetSettingsAlertRahen]"
 anb_settings.3.l:0 "£settings_button_haless££settings_alert_none£"
 anb_settings.3.lx:0 "£settings_button_haless_x£[Root.GetSettingsAlertHaless]"
 anb_settings.3.m:0 "£settings_button_insyaa££settings_alert_none£"
 anb_settings.3.mx:0 "£settings_button_insyaa_x£[Root.GetSettingsAlertInsyaa]"
 anb_settings.3.x:0 "£settings_button_back_to_menu£"
 
 #custom loc
 settings_cannor_yes:0 "£settings_cannor£"
 settings_north_aelantir_yes:0 "£settings_north_aelantir£"
 settings_forbidden_plains_yes:0 "£settings_forbidden_plains£"
 settings_bulwar_yes:0 "£settings_bulwar£"
 settings_deepwoods_yes:0 "£settings_deepwoods£"
 settings_east_serpentspine_yes:0 "£settings_east_serpentspine£"
 settings_haless_yes:0 "£settings_haless£"
 settings_north_sarhal_yes:0 "£settings_north_sarhal£"
 settings_rahen_yes:0 "£settings_rahen£"
 settings_west_serpentspine_yes:0 "£settings_west_serpentspine£"
 settings_insyaa_yes:0 "£settings_insyaa£"
 settings_south_aelantir_yes:0 "£settings_south_aelantir£"
 settings_south_sarhal_yes:0 "£settings_south_sarhal£"
 settings_no:0 ""
 
 settings_alert_orange:0 "£settings_alert_orange£"
 settings_alert_red:0 "£settings_alert_red£"
 settings_alert_red_orange:0 "£settings_alert_red_orange£"
 settings_alert_none:0 "£settings_alert_none£"
 
 settings_alert_orange_main:0 "£settings_alert_orange_main£"
 settings_alert_red_main:0 "£settings_alert_red_main£\n"
 settings_alert_none_main:0 ""
 
 #tooltip
 great_conqueror_tooltip:0 "This option will enable §YGreat Conquerors§!, for a more challenging game."
 mythical_conqueror_tooltip:0 "'Cowards shrink from challenges, weaklings flee from them, but warriors wink at them.'\n\nThis option will enable §YMythical Conquerors§!, a more extreme version of §YGreat Conquerors§!."
 random_conqueror_targets_tooltip:0 "§RWIP, does nothing for now§!"
 
 settings_conquerors_tt:0 "§YGreat Conquerors§!\nDynamically chosen AI countries will receive bonuses to help them consolidate their surroundings, to provide more challenging opponents for the middle and late game."
 settings_regions_tt:0 "§YDisabling Regions§!\nDisabling some parts of the world will allow you improve the game's performances."
 settings_needs_rom_dlc_tt:0 "§RThis feature requires the Rights of Man DLC§!"
 institutions_warning_tt:0 "£icon_settings_alert_red£ §RDisabling Cannor will prevent some Institutions from spawning correctly§!\n"
 tag_need_this_region_tt:0 "£icon_settings_alert_orange£ §y[Root.GetName] might have content related to this region§!"
 tag_in_this_region_tt:0 "£icon_settings_alert_red£ §R[Root.GetName]'s capital is in this region§!\n"
 disable_region_tt:0 "Disables this region to improve the game's performance.\n---------------------------\n"
 settings_wont_be_available_tt:0 "§RSettings are only available at the begining of the game, you won't be able to access them later.§!"
 settings_regions_are_gonna_get_removed_tt:0 "£icon_settings_alert_red£ §RDisabled regions will be removed from the game, and you won't be able to add them back latter. This action might make the game lag for a couple seconds.§!"